/**
 * id，
 * menuName==>菜单名字
 * body==>菜单里面的相关配置项
 * 只是模拟一下后台返回的数据结构,第一层的menuName是要和前端配置的动态路由名字去匹配
 * 子路由需要嵌套在children中
 */
export default {
    // 超级管理员
    'school':[
        {
            id:'001',
            menuName:'学校管理',
            body:{
                menuName:'学校管理',
                updateTime:''
            }
        },
        {
            id:'002',
            menuName:'老师管理',
            body:{
                menuName:'老师管理',
                updateTime:''
            },
            children:[
                {
                    id:'002-001',
                    menuName:'老师菜单1',
                    body:{
                        menuName:'老师菜单1',
                        updateTime:''
                    }
                },
                {
                    id:'002-002',
                    menuName:'老师菜单2',
                    body:{
                        menuName:'老师菜单2',
                        updateTime:''
                    }
                }
            ]
        },
        {
            id:'003',
            menuName:'学生管理',
            body:{
                menuName:'学生管理',
                updateTime:''
            },
            children:[
                {
                    id:'003-001',
                    menuName:'学生菜单1',
                    body:{
                        menuName:'学生菜单1',
                        updateTime:''
                    }
                },
                {
                    id:'003-002',
                    menuName:'学生菜单2',
                    body:{
                        menuName:'学生菜单2',
                        updateTime:''
                    }
                },
                {
                    id:'003-003',
                    menuName:'学生菜单3',
                    body:{
                        menuName:'学生菜单3',
                        updateTime:''
                    }
                }
            ]
        }
    ],
    //其他账号
    'other':[
        {
            id:'003',
            menuName:'学生管理',
            body:{
                menuName:'学生管理',
                updateTime:''
            },
            children:[
                {
                    id:'003-001',
                    menuName:'学生菜单1',
                    body:{
                        menuName:'学生菜单1',
                        updateTime:''
                    }
                },
                {
                    id:'003-003',
                    menuName:'学生菜单3',
                    body:{
                        menuName:'学生菜单3',
                        updateTime:''
                    }
                }
            ]
        }
    ]
}